version: '3'
services:
    app:
        image: kaangiray26/forte:2.3
        restart: on-failure
        ports:
            - "80:80"
            - "443:443"
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        environment:
            mode: local              # Set to local, public or greenlock
            port: 3000               # Set Port
            NODE_ENV: production     # Set Node Environment
            POSTGRES_HOST: postgres  # Postgres Host/IP
            POSTGRES_PORT: 5432      # Postgres Database Port
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - <library>:/library
    postgres:
        image: kaangiray26/postgres:2.0
        restart: always
        environment:
            POSTGRES_DB: forte       # Set Postgres Database Name
            POSTGRES_USER: forte     # Set Postgres Username
            POSTGRES_PASSWORD: forte # Set Postgres Password
        volumes:
            - db-data:/var/lib/postgresql/data
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U forte" ]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db-data: